### ISSUE TITLE
Review the current draft

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-struct#16]
from:  https://github.com/modelica/fmi-design/tree/master/Meetings/2024/2024-07-16-FMI-Design-Webmeeting

**Comment by TorstenBlochwitz** [comment]
Section 3.1.2. variableKind attribute values of terminal member variables
...
org.fmi-standard.fmi-ls-struct.map.domainOutput
Optionally, for each domain variable at most one array variable (typically an **input** or a local variable) can be referenced that represents calculated output value of the map. If present, a domainOutput variable must be listed directly after the corresponding codomain variable.
...
I presume this variable is typically an **output** or an a local variable.

**Comment by TorstenBlochwitz** [comment]
Section 4.3. Referencing Modelica library Combitables

We should use the correct name "Modelica Standard Library" instead of "Modelica library". I would propose to rename this section to something like: "Referencing Tables from the Modelica Standard Library"

**Comment by TorstenBlochwitz** [comment]
Section 4.3.1.1. Example:

According to the [Documentation](https://doc.modelica.org/om/[Modelica.Blocks.Tables.CombiTable1D](https://doc.modelica.org/om/Modelica.Blocks.Tables.CombiTable1D.html).html), the CombiTable1D has four additional parameters (columns, smoothness, extrapolation, verboseExtrapolation).

Shouldn't we list these parameters instead of the not existing parameter "interpolation"?

I addition to that, the codomainOutput should have the correct dimension, which is defined by the parameter columns.

**Comment by TorstenBlochwitz** [comment]
Section 5. Maps sampled on a irregular grid ("Point Cloud")

This section (especially the example) needs more elaboration. With the current text I don't understand the semantics.
